server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/capstone
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: jfc-group
      auto-offset-reset: earliest

app:
  kafka:
    topics:
      jfc-auth: jfc-auth-topic
      jfc-tool: jfc-tool-topic
      tool-jfc: tool-jfc-topic
      jfc-parser: jfc-parser-topic
      job-acknowledgement: job-acknowledgement-topic

logging:
  level:
    org.hibernate: ERROR