server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/capstone
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: jfc-group
      auto-offset-reset: latest

app:
  kafka:
    topics:
      jfc-unified: job-topic
      job-acknowledgement: job-acknowledgement-topic

logging:
  level:
    org.hibernate: ERROR